DEF_MENU_ITEMS(0, TXT_LO_QTS_LEFT, QUARTERS_LEFT)
DEF_MENU_ITEMS(1, TXT_LO_QTS_RIGHT, QUARTERS_RIGHT)
DEF_MENU_ITEMS(2, TXT_LO_QTS_TOP, QUARTERS_TOP)
DEF_MENU_ITEMS(3, TXT_LO_QTS_BOTTOM, QUARTERS_BOTTOM)

