#ifndef STATIC_TEXT_H
#define STATIC_TEXT_H

static const char *_text[53] = 
{
    "dd",
    "Kill Process",
    "github.com/drewjohnson2/mtop",
    "j",
    "Down",
    "k",
    "Up",
    "o",
    "List Additional Options",
    " Additional Options ",
    "n",
    "Sort By Process",
    "p",
    "Sort By PID",
    "c",
    "Sort By CPU Usage",
    "m",
    "Sort By Memory Usage",
    "o",
    "Close Additional Options",
    "mtop",
    "CPU Usage",
    "Memory Usage",
    "Process List",
    "Command",
    "PID",
    "CPU %",
    "Memory %",
    "Page Left",
    "h",
    "Page Right",
    "l",
    "<C-u>",
    "Jump Up",
    "<C-d>",
    "Jump Down",
    "b",
    "Return to List",
    "Status for PID %d (%s)",
    "Uptime: %u days, %02u:%02u:%02u\tLoad Average: %.2lf %.2lf %.2lf",
    "CPU %: ",
    "Memory %:",
    "State:",
    "Threads:",
    "PPid:",
    "VmRSS:",
    "VmSize:",
    "VmLock:",
    "VmData:",
    "VmStack",
    "VmSwap:",
    "VmExe:",
    "VmLib:"
};

#endif
